export const article = {
  id: 1,
  headerData: {
    isFavourite: true,
    title: 'Невероятные новости',
    lastUpdatedAt: '2 минуты',
    postsCount: 42,
    sourcesCount: 18,
  },

  whatsNew: [
    {
      id: 1,
      time: '2026-01-15T09:10:00Z',
      title: 'Та самая новость о которой все говорят',
      confirmed: 1,
    },
    {
      id: 2,
      time: '2026-01-14T18:45:00Z',
      title: 'Вы не поверите, но это реально случилось',
      confirmed: 1,
    },
    {
      id: 3,
      time: '2026-01-13T11:20:00Z',
      title: 'Это будет лучшее приложение для создания новостей',
      confirmed: 0,
    },
  ],

  allSources: [
    {
      id: 101,
      time: '2026-01-15T08:55:00Z',
      sourceName: 'Имя источника',
      title: 'Об этой новости говорят все',
      outerLink: 'https://google.com',
    },
    {
      id: 102,
      time: '2026-01-14T16:30:00Z',
      sourceName: 'Имя источника',
      title: 'Читайте именно эту новость',
      outerLink: 'https://google.com',
    },
    {
      id: 103,
      time: '2026-01-13T10:05:00Z',
      sourceName: 'Имя источника',
      title: 'Узрите правду, все в этой новости',
      outerLink: 'https://google.com',
    },
  ],
};

export const favourites = [
  {
    id: 1,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 2,
    title: 'title 2',
    badgeText: 'badgeText 2',
    lastUpdateTitle: 'lastUpdateTitle 2',
    lastUpdateText: 'lastUpdateText 2',
    firstUpdateTitle: 'firstUpdateTitle 2',
    firstUpdateText: 'firstUpdateText 2',
    postsCount: 2,
    sourceCount: 2,
    lastUpdatedAt: 'lastUpdatedAt 2',
  },
];

export const restEvents = [
  {
    id: 1,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 2,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title2',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 3,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title1',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 4,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title3',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 5,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title4',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 6,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title5',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
  {
    id: 7,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title6',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: 'lastUpdatedAt',
  },
];

export const streamEvents = [
  {
    id: 1,
    source: 'string',
    time: '2026-01-21 10:00',
    title: 'Событие 1',
    originalLink: 'string',
    localLink: 'string',
    imageUrl: 'https://placehold.co/600x400',
    type: 'type1',
    period: '24 часа',
  },
  {
    id: 2,
    source: 'string2',
    time: '2026-01-20 12:00',
    title: 'Событие 2',
    imageUrl: 'https://placehold.co/600x400',
    subtitle: 'Описание 2',
    originalLink: 'string',
    localLink: 'string',
    type: 'type2',
    period: 'Неделя',
  },
];

export const summaryMap = [
  {
    id: 'string1',
    time: '15:10',
    title: 'Заголовок 1',
    sourceName: 'РИА',
    confirmed: 6,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string2',
    time: '15:11',
    title: 'Заголовок 2',
    sourceName: 'РИА',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string3',
    time: '15:12',
    title: 'Заголовок 3',
    sourceName: 'РИА',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string4',
    time: '15:13',
    title: 'Заголовок 4',
    sourceName: 'РИА',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string5',
    time: '15:14',
    title: 'Заголовок 5',
    sourceName: 'РИА',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string6',
    time: '15:15',
    title: 'Заголовок 6',
    sourceName: 'ТАСС',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string7',
    time: '15:16',
    title: 'Заголовок 7',
    sourceName: 'ТАСС',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string8',
    time: '15:17',
    title: 'Заголовок 8',
    sourceName: 'ТАСС',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string9',
    time: '15:18',
    title: 'Заголовок 9',
    sourceName: 'ТАСС',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: 'string10',
    time: '15:19',
    title: 'Заголовок 10',
    sourceName: 'ТАСС',
    confirmed: 2,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
];
