export const article = {
  id: 1,
  headerData: {
    isFavourite: true,
    title: 'Невероятные новости',
    lastUpdatedAt: '2 минуты',
    postsCount: 42,
    sourcesCount: 18,
  },

  whatsNew: [
    {
      id: 1,
      time: '2026-01-15T09:10:00Z',
      title: 'Та самая новость о которой все говорят',
      confirmed: 1,
    },
    {
      id: 2,
      time: '2026-01-14T18:45:00Z',
      title: 'Вы не поверите, но это реально случилось',
      confirmed: 1,
    },
    {
      id: 3,
      time: '2026-01-13T11:20:00Z',
      title: 'Это будет лучшее приложение для создания новостей',
      confirmed: 0,
    },
  ],

  allSources: [
    {
      id: 101,
      time: '2026-01-15T08:55:00Z',
      sourceName: 'tass',
      title: 'Об этой новости говорят все',
      outerLink: 'https://google.com',
    },
    {
      id: 102,
      time: '2026-01-14T16:30:00Z',
      sourceName: 'ria',
      title: 'Читайте именно эту новость',
      outerLink: 'https://google.com',
    },
    {
      id: 103,
      time: '2026-01-13T10:05:00Z',
      sourceName: 'lenta',
      title: 'Узрите правду, все в этой новости',
      outerLink: 'https://google.com',
    },
  ],
};

export const favourites = [
  {
    id: 1,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 2,
    title: 'title 2',
    badgeText: 'badgeText 2',
    lastUpdateTitle: 'lastUpdateTitle 2',
    lastUpdateText: 'lastUpdateText 2',
    firstUpdateTitle: 'firstUpdateTitle 2',
    firstUpdateText: 'firstUpdateText 2',
    postsCount: 2,
    sourceCount: 2,
    lastUpdatedAt: '2 мин',
  },
];

export const restEvents = [
  {
    id: 1,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 2,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title2',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 3,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title1',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 4,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title3',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 5,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title4',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 6,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title5',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
  {
    id: 7,
    imageUrl: 'https://placehold.co/600x400',
    title: 'title6',
    lastUpdateTitle: 'lastUpdateTitle',
    lastUpdateText: 'lastUpdateText',
    firstUpdateTitle: 'firstUpdateTitle',
    firstUpdateText: 'firstUpdateText',
    postsCount: 3,
    sourceCount: 1,
    lastUpdatedAt: '2 мин',
  },
];

export const streamEvents = [
  {
    id: 1,
    source: 'string',
    time: '2026-01-21 10:00',
    title: 'Событие 1',
    originalLink: 'string',
    localLink: 'string',
    imageUrl: 'https://placehold.co/600x400',
    type: 'type1',
    period: '24 часа',
  },
  {
    id: 2,
    source: 'string2',
    time: '2026-01-20 12:00',
    title: 'Событие 2',
    imageUrl: 'https://placehold.co/600x400',
    subtitle: 'Описание 2',
    originalLink: 'string',
    localLink: 'string',
    type: 'type2',
    period: 'Неделя',
  },
];

const confirmedMap = [
  {
    id: 1,
    sourceName: 'ria',
    link: 'string',
  },
  {
    id: 2,
    sourceName: 'ria',
    link: 'string',
  },
  {
    id: 3,
    sourceName: 'ria',
    link: 'string',
  },
  {
    id: 4,
    sourceName: 'ria',
    link: 'string',
  },
];

export const summaryMap = [
  {
    id: 'string1',
    time: '15:10',
    title: 'ЦБ раздает всем желающим деньги для борьбы с инфляцией',
    sourceName: 'ria',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string2',
    time: '15:11',
    title: 'ЦБ отнимает деньги у бедняков для помощи миллиардерам',
    sourceName: 'ria',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string3',
    time: '15:12',
    title: 'ЦБ напечатал 1 триллион долларов',
    sourceName: 'ria',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string4',
    time: '15:13',
    title: 'Тикток запретили в россии',
    sourceName: 'ria',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string5',
    time: '15:14',
    title: 'ЦБ просит Руслана Москвитина улыбнуться',
    sourceName: 'ria',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string6',
    time: '15:15',
    title: 'МИД РФ будет разбираться с беспорядком за границей',
    sourceName: 'tass',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    additionalSources: [
      {
        id: 'string6_1',
        time: '15:18',
        title: 'Заголовок 6_1',
        sourceName: 'tass',
        confirmed: confirmedMap,
        outerLink: 'string',
        link: 'string',
        fullText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      },
      {
        id: 'string6_2',
        time: '15:19',
        title: 'Заголовок 6_2',
        sourceName: 'tass',
        confirmed: confirmedMap,
        outerLink: 'string',
        link: 'string',
        fullText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      },
      {
        id: 'string6_3',
        time: '15:22',
        title: 'Заголовок 6_2',
        sourceName: 'ria',
        confirmed: confirmedMap,
        outerLink: 'string',
        link: 'string',
        fullText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      },
      {
        id: 'string6_4',
        time: '15:25',
        title: 'Заголовок 6_2',
        sourceName: 'tass',
        confirmed: confirmedMap,
        outerLink: 'string',
        link: 'string',
        fullText:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      },
    ],
  },
  {
    id: 'string7',
    time: '15:16',
    title: 'Чувствую себя снова молодым, мне помог простой советский...',
    sourceName: 'tass',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string8',
    time: '15:17',
    title: 'ЦБ заявил, что интересные новости закончились',
    sourceName: 'tass',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string9',
    time: '15:18',
    title: 'Заголовок 9',
    sourceName: 'tass',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
  {
    id: 'string10',
    time: '15:19',
    title: 'Заголовок 10',
    sourceName: 'tass',
    confirmed: confirmedMap,
    outerLink: 'string',
    link: 'string',
    fullText:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  },
];

export const sourcesMap = [
  {
    id: 'src_123',
    name: 'ТАСС',
    url: 'rbc.ru',
    type: 'smi',
    region: 'Москва',
    is_active: true,
    frequency_minutes: 5,
    logo_url: 'https://cdn.example.com/logos/tass.png',
  },
  {
    id: 'src_124',
    name: 'РБК',
    url: 'tass.ru',
    type: 'ia',
    region: 'Россия',
    is_active: true,
    frequency_minutes: 5,
    logo_url: 'https://cdn.example.com/logos/tass.png',
  },
  {
    id: 'src_125',
    name: 'РИА',
    url: 'kommersant.ru',
    type: 'press',
    region: 'Россия',
    is_active: false,
    frequency_minutes: 5,
    logo_url: 'https://cdn.example.com/logos/tass.png',
  },
];
